### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by cobrowserAlex** [skippbox/kmachine#23]
I did a clean install and followed the instructions to create a Kmachine, but cannot connect, even after allowing a few minutes to start everything.
```
$ kmachine create -d virtualbox publiccloud
Running pre-create checks...
Creating machine...
Waiting for machine to be running, this may take a few minutes...
Machine is running, waiting for SSH to be available...
Detecting operating system of created instance...
Provisioning created instance...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Configuring kubernetes...
Copying certs to the remote system...
To see how to connect Docker to this machine, run: kmachine env publiccloud
$ kmachine env publiccloud
kubectl config set-cluster publiccloud --server=https://192.168.99.101:6443 --insecure-skip-tls-verify=false
kubectl config set-cluster publiccloud --server=https://192.168.99.101:6443 --certificate-authority=/Users/alexknol/.kube/machine/machines/publiccloud/ca.pem
kubectl config set-credentials publiccloud --token=1dylmUdE73QhkPi3pF6peTNjI7z3hWqo
kubectl config set-context publiccloud --user=publiccloud --cluster=publiccloud
kubectl config use-context publiccloud
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.101:2376"
export DOCKER_CERT_PATH="/Users/alexknol/.kube/machine/machines/publiccloud"
export DOCKER_MACHINE_NAME="publiccloud"
# Run this command to configure your shell:
# eval "$(kmachine env publiccloud)"
$ eval "$(kmachine env publiccloud)"
cluster "publiccloud" set.
cluster "publiccloud" set.
user "publiccloud" set.
context "publiccloud" set.
switched to context "publiccloud".
$ kubectl get pods
error: couldn't read version from server: Get https://192.168.99.101:6443/api: dial tcp 192.168.99.101:6443: connection refused
$ kubectl get pods
error: couldn't read version from server: Get https://192.168.99.101:6443/api: dial tcp 192.168.99.101:6443: connection refused
```

**Comment by runseb** [comment]
@cobrowserAlex thanks for reporting this, I am looking into it right now. I think it's pulling an old box image of boot2k8s, pinging @cab105 

will get back asap.

**Comment by cobrowserAlex** [comment]
@cab105 thanks. I have to mention, that it has worked, but when I opened my macbook this morning i saw this. even after rebuilding.

**Comment by runseb** [comment]
@cobrowserAlex ah good to know. I think there is an issue when the VM goes into pause...it seems the services don't come back up properly.

**Comment by cab105** [comment]
I am able to reproduce by setting up a new VirtualBox vm and suspending my Linux based laptop overnight.  I will work on reproducing with VMWare in order to determine if its specific to kmachine.

**Comment by cobrowserAlex** [comment]
When I check inside the kmachine, I also do not get a response on curl https://localhost:6443 on on 8080 (http)

**Comment by runseb** [comment]
@cobrowserAlex I presume that you are still on virtualbox.

Can you try to do a:

`kmachine regenerate-certs <machine_name>`

then a 

`kmachine env <machine_name`

then check that the hypercube images are being pulled by running `docker images`

**Comment by cobrowserAlex** [comment]
Thanks, that worked!
I now also know that it takes a minute to respond....

**Comment by runseb** [comment]
Great, glad it worked.
I am going to upload a new version tomorrow...
