### ISSUE TITLE
Run kubelet as service and not in docker

### ISSUE THREAD

**Issue by runseb** [skippbox/kmachine#26]
Considering the many issues with running the kubelet in a container, we might consider running it as a service like for virtualbox.

`libmachine/provision/utils.go` runs is as a container...

**Comment by runseb** [comment]
closed by #35

**Comment by tdeheurles** [comment]
Looking to the code, I can see some dependencies to 1.2.0-alpha.8 but we are running a 1.1.2 kubernetes.

Also, do you have seen the last update from https://github.com/kubernetes/kubernetes/issues/4869 ? The kubelet issue with volumes seems really close to be fixed.

**Comment by runseb** [comment]
@tdeheurles yeah, I spent quite a bit of time looking at all the PR and issues on containerized Kubelet. While it might get fixed, we are trying to run kubelet directly as a service on the node. It looks more stable and less prone to changes.

**Comment by tdeheurles** [comment]
**It looks more stable and less prone to changes.**. 
I think you're right.
