### ISSUE TITLE
How to use a debian image on virtualbox? how to define the debian image?

### ISSUE THREAD

**Issue by sharminakteranee** [skippbox/kmachine#36]

**Comment by runseb** [comment]
@sharminakteranee on virtualbox we use boot2k8s which is based on a debian:jessie image.

What are you trying to do ?

**Comment by sharminakteranee** [comment]
I want to use my custom image, Is that possible?

**Comment by runseb** [comment]
ah yes:

```
$kmachine create -d virtualbox --virtualbox-boot2docker-url=<LOCATION_OF_YOUR_ISO>
```

**Comment by sharminakteranee** [comment]
Thank you.
But I need to create the iso image first. How can I create that?

**Comment by runseb** [comment]
with boot2k8s , the other issue you opened skippbox/boot2k8s

**Comment by runseb** [comment]
it is the same than with docker-machine.
You can specify a custom ISO with the --virtualbox-boot2docker-url option.
if you want to build a boot2docker variant ISO, then use boot2k8s which gives you Kubernetes.

**Comment by sharminakteranee** [comment]
Ok, Thank You :)
