### ISSUE TITLE
DNS support

### ISSUE THREAD

**Issue by apobbati** [skippbox/kmachine#37]
Inter-container DNS resolution is not working. Are there plans to support this by enabling the DNS add-on ?

**Comment by runseb** [comment]
Hi @apobbati why do you say it does not work ?
The DNS add-on is not started by default we are working on that, but if you install it DNS will work just fine.

**Comment by apobbati** [comment]
Right. I meant that the DNS add-on was not started by default.
I could send a PR to help out. Where is a good place to start looking?

Thanks

**Comment by runseb** [comment]
@apobbati ok got it. We are working on this. you can help by looking at

`https://github.com/skippbox/kmachine/blob/kmachine/libmachine/provision/generic.go`
and
`https://github.com/skippbox/kmachine/blob/kmachine/libmachine/provision/utils.go`

**Comment by sebgoa** [comment]
I am closing it, because it is fixed in 1.2.0 and 1.2.1
