### ISSUE TITLE
Allowing changing Kubernetes version without downloading new version of kmachine

### ISSUE THREAD

**Issue by wstrange** [skippbox/kmachine#39]
It would be nice  if the Kubernetes version was not tied to the version of kmachine

For example, if I wanted to try the latest alpha build of 1.3, or use some previous version. 

Perhaps a command line flag when the machine is built?

**Comment by runseb** [comment]
@wstrange yes, that's actually a very good idea.

**Comment by runseb** [comment]
maybe we can keep the version in sync which would give us the hint of what would run by default. But you could override the k8s version:

```
kmachine create -d digitaocean -v 1.3.0-alpha.1 foobar
```

@cab105 this might be an easy fix in the go template for the manifest.

**Comment by runseb** [comment]
@wstrange : this is fixed in master with:

https://github.com/skippbox/kmachine/commit/71320c7385eb250d4a766e6d559c8be35c2724fc

It will be in the next release.

I am closing this.
