### ISSUE TITLE
Handle case of existing boot2docker.iso file

### ISSUE THREAD

**Issue by runseb** [skippbox/kmachine#9]
we probably want to download boot2k8s.iso specifically, in case there is an existing boot2dock.iso on the system,...or will it provision k8s on this existing boot2docker image ?

**Comment by tdeheurles** [comment]
- What if boot2docker image change ? 
- You also need to manage boot2docker to k8s and boot2k8s.
Forcing the download of some Mb at the start of container project is not a problem.

A script to force the boot2k8s download seems better.

**Comment by runseb** [comment]
Actually that's an old issue, I think it is solved right now because we moved from using the `~/.docker` directory to using our own in `~/.kube` and we are also pointing to boot2k8s.iso from https://github.com/skippbox/boot2k8s . It will fetch the latest release of boot2k8s and stick it in the cache directory under `~/.kube`.

**Comment by runseb** [comment]
Fixed by 3d5f153ed44f7ffee011a5ddac84ff782112191d
